# DATA CONFIGURATION
data:
  raw_path: "data/raw/RatesRegimes.parquet"
  econ_reports: "data/raw/econ_reports.parquet"
  econ_jobs: "data/raw/econ_jobs.parquet"
  processed_path: "data/processed/"
  
  # Treasury curve tenors to use
  tenors: ["USGG2YR Index", "USGG3YR Index", "USGG5YR Index", 
           "USGG7YR Index", "USGG10YR Index", "USGG30YR Index"]
  
  # Maturity mapping (in years)
  maturities: [2, 3, 5, 7, 10, 30]

# AFNS MODEL
afns:
  estimation_window: 252     # Rolling window for parameter estimation
  lambda: 0.0609             # Nelson-Siegel lambda
  measurement_noise_R: 4.0   # Fixed measurement noise variance (bps²)

# REGIME EMBEDDING - UPDATED FOR PERSISTENCE
regime:
  vol_window: 60              
  inflation_halflife: 21      
  n_states_range: [2, 3, 4, 5]
  sticky_alpha: 100.0        # INCREASED from 10 -> 100 for multi-month persistence
  random_state: 42            
  
  # Regime-dependent volatility scaling
  volatility_scaling:
    use_scaled_Q: true       # Scale Q matrix by regime
    scale_method: "trace_ratio"  # How to compute scaling factor

# SCENARIO GENERATION - MULTI-YEAR HORIZONS
scenarios:
  confidence_levels: [0.05, 0.5, 0.95]
  n_paths: 10000          
  n_jobs: -1              
  
  # Multi-year horizons for reinvestment analysis
  horizons:
    '6m': 126      # 6 months
    '1y': 252      # 1 year
    '2y': 504      # 2 years  
    '3y': 756      # 3 years
    '5y': 1260     # 5 years
  
  # Fed scenario shocks (basis points)
  fed_shocks: [-200, -100, -50, 0, 50, 100, 200]

# VALIDATION - MULTI-HORIZON
validation:
  # Test horizons must match scenario horizons
  test_horizons: [126, 252, 504, 756, 1260]  # 6M, 1Y, 2Y, 3Y, 5Y
  
  # Backtesting configuration
  backtest:
    start_date: "2015-01-01"  # Start of out-of-sample test
    refit_frequency: "quarterly"  # How often to re-estimate models
    min_training_years: 5  # Minimum history required
  
  subsample_splits:
    - ["2010-01-01", "2015-12-31"]  # Pre-liftoff
    - ["2016-01-01", "2019-12-31"]  # Normalization
    - ["2020-01-01", "2025-09-30"]  # COVID+
  
  # DV01 weights for error calculation
  dv01_weights: [0.1, 0.1, 0.2, 0.15, 0.35, 0.1]
  
  # Coverage test tolerance
  coverage_tolerance: 0.05
  
  # Multi-horizon specific settings
  multi_horizon:
    validate_consistency: true  # Check that short/long horizons align
    max_horizon_years: 5  # Maximum forecast horizon

# OUTPUT
output:
  figures_path: "outputs/figures/"
  results_path: "outputs/results/"
  scenarios_path: "outputs/scenarios/"
